### PR TITLE
Allow customizing the import style

### PR DESCRIPTION
**Pull request by ArneBab**
For https://github.com/jakoblind/js-import/issues/8

### CODE REVIEW

**Comment by jakoblind** [comment]
Nice! could you add some info about what this is and how to use it in the README? that would be nice, so that others can benefit from this feature also. Thanks!

**Comment by ArneBab** [comment]
I added a "Customization" section to the readme for quoting style and import style.

**Comment by jakoblind** [comment]
Thanks @ArneBab !

**Comment by ArneBab** [comment]
Thank you for creating and maintaining js-import!

**Pull request merged**
