### PR TITLE
Handle edge cases better.

### PR DESCRIPTION
**Pull request by renatofdds**
New interface:
- No prefix argument: Import default export from module.
- One prefix argument: Imports exported symbols from module.
- Two prefix arguments: Import all exported symbols from module.

### CODE REVIEW

**Comment by jakoblind** [comment]
This is a good improvement! We need to also update the README file. Do you have time? Otherwise I will do it this weekend.

**Comment by renatofdds** [comment]
Done.

**Comment by jakoblind** [comment]
Awesome!

**Comment by renatofdds** [comment]
Thank you!

**Pull request merged**
